---
title: "Assignment2"
author: "Zichu Wei u7457435"
date: "2022/10/29"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Provide the link about my GitHub Repo 

[My GitHub Repository](https://github.com/ZichuWei/Pickled-fish-ZW)


## Statistical Analysis and Interpretation

### Load the necessary R Packages:

```{r,results='hide'}
# Data processing:
library(tidyverse)
library(readr)
library(dplyr)
library(plotrix)
```

```{r}
# Meta_analysis:
library(pacman)
pacman::p_load(metafor, orchaRd)
p_load(bookdown, devtools, tidyverse, ggforce, GGally, flextable, latex2exp, png,
    magick, metafor, MASS, emmeans, R.rsp)
devtools::install_github("daniel1noble/orchaRd", force = TRUE)
library(orchaRd)
```

```{r}
# Draw the figures:
library(ggplot2)
```


### Read the files:

```{r}
# These analyses need these three files.
data <- read.csv("OA_activitydat_20190302_BIOL3207.csv")
paper <- read.csv("clark_paper_data.csv")
meta <- read.csv("ocean_meta_data.csv")
```

### Process and clean the original data:

```{r}
# Drop irrelevant columns 'loc' and 'comment':
data_clean <- subset(data,select = -c(loc, comment))
# Remove the missing data, which reflected by 'NA';
# Remove the incorrect data: some data cannot less than 0, so use filter to check and correct the data.
data_eff <- data_clean %>% filter(!is.na(activity)) %>% filter(animal_id > 0, activity > 0)
data_eff
```

```{r}
# Check spelling in species and treatment:
data_eff$species %>% unique()
data_eff$treatment %>% unique()
```

```{r}
# Because we find that there are six species and two treatments which are all correct, so we don't need to change or remove some data.
```



